name: Backend CI for non-main branches
  
on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-branch-ci.yml'
    branches-ignore:
      - main
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-branch-ci.yml'
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build backend/Backend --configuration Release

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: .

  test:
    runs-on: windows-latest
    needs: build
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore backend/Backend.Tests

      - name: Install report generator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.1.21

      - name: Build the test project
        run: dotnet build backend/Backend.Tests --configuration Release --no-restore

      - name: Run unit tests with coverage
        run: dotnet test backend/Backend.Tests --configuration Release -- collect:"XPlat Code Coverage" --results-directory ./TestResults

      - name: Generate code coverage report
        run: reportgenerator \
          -reports:./TestResults/**/coverage.cobertura.xml \
          -targetdir:"coveragereport" \
          -reporttypes:Html

      - name: Upload code coverage report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coveragereport