name: Backend CI
  
on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
    branches-ignore:
      - main
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build backend/Backend --configuration Release

  unit-test:
    runs-on: windows-latest
    needs: build
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore backend/Backend.Tests

      - name: Install report generator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.1.21

      - name: Build the test project
        run: dotnet build backend/Backend.Tests --configuration Release --no-restore

      - name: Run unit tests with coverage
        run: dotnet test backend/Backend.Tests --configuration Release --collect:"XPlat Code Coverage"

      - name: Generate code coverage report
        run: reportgenerator \
          -reports:./backend/Backend.Tests/TestResults/**/coverage.cobertura.xml \
          -targetdir:"coveragereport" \
          -reporttypes:Html

      - name: Upload code coverage report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coveragereport
  integration-test:
    runs-on: windows-latest
    needs: build
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore backend/Backend.IntegrationTests

      - name: Build the test project
        run: dotnet build backend/Backend.IntegrationTests --configuration Release --no-restore

      - name: Run tests
        run: dotnet test backend/Backend.IntegrationTests --configuration Release