name: Build and Deploy Docs

on:
  workflow_run:
    workflows: ["Main Backend CI/CD", "Main Frontend CI/CD"]
    types:
      - completed

jobs:
  build_and_deploy_docs:
    runs-on: ubuntu-latest
    name: Build and Deploy Docs
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Specify the Node.js version to use

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Generate Frontend Documentation
        working-directory: ./frontend
        run: npx compodoc -p tsconfig.json -d _compodoc

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install DocFX
        run: dotnet tool install -g docfx

      - name: Generate Backend Documentation
        run: docfx build ./backend/Backend/docfx.json
      
      - name: Download Code Coverage Report
        uses: actions/download-artifact@v4
        with:
          name: code-coverage-report-deploy
          path: coveragereport

      - name: Merge Docs
        run: |
          rm -rf docs
          mkdir -p docs/backend
          mkdir -p docs/frontend
          mkdir -p docs/coveragereport
          cp -r ./frontend/_compodoc/* docs/frontend/
          cp -r ./backend/Backend/_site/* docs/backend/
          cp -r ./coveragereport/* docs/coveragereport/

      # Create a root landing page for the documentation to account for both frontend and backend
      - name: Add Root Landing Page
        run: |
          cat <<EOF > docs/index.html
          <!DOCTYPE html>
          <html>
            <head><title>Smart Meal Planner Documentation</title></head>
            <body>
              <h1>Smart Meal Planner Documentation</h1>
              <ul>
                <li><a href="frontend/">Frontend Angular Docs</a></li>
                <li><a href="backend/">Backend ASP.NET Core Docs</a></li>
                <li><a href="http://https://smart-meal-planner-backend-ceazgjcaehfghdf7.canadacentral-01.azurewebsites.net/swagger">API Docs</a></li>
              </ul>
            </body>
          </html>
          EOF

      - name: Deploy
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_POND_0787B270F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          skip_app_build: true
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "docs" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_POND_0787B270F }}
          action: "close"
