#name: Build and Deploy Backend to Azure

#on:
#  push:
#    branches:
#      - main  # Change if using a different branch

#jobs:
#  build-and-deploy:
#    runs-on: windows-latest

#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v4

#    - name: Set up .NET
#      uses: actions/setup-dotnet@v4
#      with:
#        dotnet-version: '8.0.x'

#    - name: Restore dependencies
#      run: dotnet restore backend/Backend

#    - name: Build
#      run: dotnet build backend/Backend --configuration Release --no-restore

#    - name: Publish
#      run: dotnet publish backend/Backend -c Release -o publish

#    - name: Deploy to Azure Web App
#      uses: azure/webapps-deploy@v2
#      with:
#        app-name: 'smart-meal-planner-backend'
#        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
#        package: publish


# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Backend CI/CD
  
on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/main_smart-meal-planner-backend.yml'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build backend/Backend --configuration Release

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: .

      - name: Generate OpenAPI docs
        run: swagger tofile --output ./openapi.json ./backend/bin/Debug/net8.0/Backend.dll v1

      - name: Upload API docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-openapi
          path: ./openapi.json

  test:
    runs-on: windows-latest
    needs: build
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Run unit tests
        run: dotnet test backend/Backend.Tests --configuration Release

  deploy:
    runs-on: windows-latest
    needs: [build, test]
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: dotnet publish
        run: dotnet publish backend/Backend -c Release -o publish
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7A381B7694AE46BAA4F949F9CEE439E8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_167812655C614B57BE44E4AECBADFD1F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BB25C7AB8A5B443CADF01DB91FD1330E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'smart-meal-planner-backend'
          slot-name: 'Production'
          package: .